services:

  config-service:
    build: ../config-service
    image: config-service:latest
    ports:
      - "8888:8888"
    container_name: config-service
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - private_net

  discovery-service:
    build: ../discovery-service
    image: discovery-service:latest
    ports:
      - "8761:8761"
    container_name: discovery-service
    networks:
      - private_net
      - public_net
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888

    depends_on:
      config-service:
        condition: service_healthy

  gateway-service:
    build: ../gateway-service
    image: gateway-service:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      config-service:
        condition: service_healthy
      discovery-service:
        condition: service_started
    container_name: gateway-service
    networks:
      - private_net
      - public_net

  book-service:
    build: ../book-service
    image: book-service:latest
    ports:
      - "8081:8081"
    environment:
      - SPRING_CONFIG_IMPORT=configserver:http://config-service:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      postgres:
        condition: service_started
      config-service:
        condition: service_healthy
    container_name: book-service
    networks:
      - private_net
      - public_net

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=librarydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres
    networks:
      - private_net
      - public_net


volumes:
  postgres_data:

networks:
  public_net:
  private_net:
    internal: true
